package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// moonlitConfPath is the single file the app generates for Hyprland. It's
// sourced LAST from hyprland.conf, so its values win over the base config.
func moonlitConfPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".config", "hypr", "moonlit.conf")
}

// renderHyprConf turns the app's Hyprland + keybind settings into a Hyprland
// config fragment. Keybinds unbind their default first so overrides are clean
// (no double-firing).
func renderHyprConf(c Config) string {
	var b strings.Builder
	b.WriteString("# ─────────────────────────────────────────────────────────────\n")
	b.WriteString("# Generated by moonlit-settings — DO NOT EDIT BY HAND.\n")
	b.WriteString("# Sourced last from hyprland.conf, so these values win.\n")
	b.WriteString("# ─────────────────────────────────────────────────────────────\n\n")

	h := c.Hypr

	b.WriteString("general {\n")
	fmt.Fprintf(&b, "    gaps_in = %d\n", h.GapsIn)
	fmt.Fprintf(&b, "    gaps_out = %d\n", h.GapsOut)
	fmt.Fprintf(&b, "    border_size = %d\n", h.BorderSize)
	if h.BorderOverride {
		fmt.Fprintf(&b, "    col.active_border = rgb(%s)\n", strings.TrimPrefix(h.BorderActive, "#"))
		fmt.Fprintf(&b, "    col.inactive_border = rgb(%s)\n", strings.TrimPrefix(h.BorderInactive, "#"))
	}
	b.WriteString("}\n\n")

	b.WriteString("decoration {\n")
	fmt.Fprintf(&b, "    rounding = %d\n", h.Rounding)
	fmt.Fprintf(&b, "    active_opacity = %.2f\n", h.ActiveOpacity)
	fmt.Fprintf(&b, "    inactive_opacity = %.2f\n", h.InactiveOpacity)
	fmt.Fprintf(&b, "    blur {\n        enabled = %t\n        size = %d\n    }\n", h.BlurEnabled, h.BlurSize)
	fmt.Fprintf(&b, "    shadow {\n        enabled = %t\n    }\n", h.ShadowEnabled)
	b.WriteString("}\n\n")

	fmt.Fprintf(&b, "animations {\n    enabled = %t\n}\n\n", h.AnimEnabled)

	if len(c.Keybinds) > 0 {
		b.WriteString("# Keybind overrides (unbind default, then rebind)\n")
		for _, kb := range c.Keybinds {
			if kb.Combo == kb.Default {
				continue
			}
			fmt.Fprintf(&b, "unbind = %s\n", kb.Default)
			fmt.Fprintf(&b, "bind = %s, %s\n", kb.Combo, kb.Dispatcher)
		}
		b.WriteString("\n")
	}
	return b.String()
}

// applyHypr writes moonlit.conf, makes sure hyprland.conf sources it, then
// reloads. This is the "hard change" path behind the Apply button.
func applyHypr(c Config) error {
	if err := os.WriteFile(moonlitConfPath(), []byte(renderHyprConf(c)), 0o644); err != nil {
		return err
	}
	if err := ensureSourced(); err != nil {
		return err
	}
	out, err := exec.Command("hyprctl", "reload").CombinedOutput()
	if err != nil {
		return fmt.Errorf("hyprctl reload: %v: %s", err, strings.TrimSpace(string(out)))
	}
	return nil
}

// ensureSourced appends `source = .../moonlit.conf` to hyprland.conf once, as
// the last line so it overrides everything above it.
func ensureSourced() error {
	home, _ := os.UserHomeDir()
	main := filepath.Join(home, ".config", "hypr", "hyprland.conf")
	data, err := os.ReadFile(main)
	if err != nil {
		return err
	}
	line := "source = ~/.config/hypr/moonlit.conf"
	if strings.Contains(string(data), line) {
		return nil
	}
	body := string(data)
	if !strings.HasSuffix(body, "\n") {
		body += "\n"
	}
	body += "\n# moonlit-settings generated overrides (must stay last)\n" + line + "\n"
	return os.WriteFile(main, []byte(body), 0o644)
}
