package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// rofiColorsPath is the generated file config.rasi's @theme points at. It
// chain-imports the base theme itself (see renderRofiColors) because this
// rofi version does not cascade multiple @theme lines in one config file —
// a second @theme resets everything to rofi's built-in defaults instead of
// layering on top.
func rofiColorsPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".config", "rofi", "themes", "moonlit-colors.rasi")
}

func rofiBaseThemePath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".config", "rofi", "themes", "catppuccin-mocha.rasi")
}

func rofiConfigPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".config", "rofi", "config.rasi")
}

// renderRofiColors imports the base catppuccin theme, then overrides just
// the accent ("pink") variable it uses for the prompt icon and the
// selected-item border.
func renderRofiColors(c Config) string {
	var b strings.Builder
	b.WriteString("/* Generated by moonlit-settings — DO NOT EDIT BY HAND. */\n")
	fmt.Fprintf(&b, "@theme %q\n", rofiBaseThemePath())
	b.WriteString("* {\n")
	fmt.Fprintf(&b, "    pink: %s;\n", c.RofiAccent)
	b.WriteString("}\n")
	return b.String()
}

// applyRofi writes the override file and makes sure config.rasi sources it.
// Rofi re-reads its theme fresh on every launch, so no reload step is needed.
func applyRofi(c Config) error {
	if err := os.MkdirAll(filepath.Dir(rofiColorsPath()), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(rofiColorsPath(), []byte(renderRofiColors(c)), 0o644); err != nil {
		return err
	}
	return ensureRofiSourced()
}

var rofiThemeLineRe = regexp.MustCompile(`(?m)^@theme\s+".*"\s*$`)

// ensureRofiSourced points config.rasi's @theme at the generated file,
// replacing any existing @theme line(s) rather than appending — this rofi
// version only honors the last one, and stacking multiple breaks styling.
func ensureRofiSourced() error {
	p := rofiConfigPath()
	data, err := os.ReadFile(p)
	if err != nil {
		return err
	}
	target := fmt.Sprintf(`@theme "%s"`, rofiColorsPath())
	body := string(data)

	lines := strings.Split(body, "\n")
	var out []string
	found := false
	for _, l := range lines {
		if rofiThemeLineRe.MatchString(l) {
			if !found {
				out = append(out, target)
				found = true
			}
			continue
		}
		out = append(out, l)
	}
	if !found {
		out = append(out, target)
	}
	newBody := strings.Join(out, "\n")
	if newBody == body {
		return nil
	}
	return os.WriteFile(p, []byte(newBody), 0o644)
}
