source = ~/.config/hypr/monitors.conf

env = QT_QPA_PLATFORMTHEME,xdgdesktopportal
env = GTK_USE_PORTAL,1
env = GDK_BACKEND,wayland

source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/keybinds.conf

# Look & feel
source = ~/.config/hypr/general.conf
source = ~/.config/hypr/decoration.conf
source = ~/.config/hypr/animations.conf
