# Input
input {
    touchpad {
        natural_scroll = true
        tap-to-click = true
        disable_while_typing = true
        drag_lock = true
        scroll_factor = 0.7
    }
    scroll_method = 2fg
}
